"""
scripts/assemble_features.py
-----------------------------
Assembles the final feature matrix for a given Point-in-Time anchor.

Combines three feature groups into a single per-founder feature matrix:
    1. **Structural Embeddings**: 64-dimensional Word2Vec node embeddings from
       ``data/embeddings_{t_anchor}.csv``, generated by ``train_embeddings.py``.
    2. **Network Centrality Metrics**: PageRank, Degree, Eigenvector, Clustering
       Coefficient, Closeness, **Betweenness**, **Coreness**, and **Degree Assortativity**.
    3. **Temporal Community Features**: **Louvain Community ID** and **Primary Mafia ID** 
       (the largest 3-year rolling company-period bucket a founder belongs to).
    4. **Neighborhood Success Rate (VC Alpha)**: Percentage of a founder's 1st-degree
       neighbors who achieved outlier success (top 15% PEV) prior to ``t_anchor``.
    5. **Profile Performance**: Prior capital, senior roles, **years of experience**,
       **career velocity**, and **serial founder count**.

The output is saved to ``data/feature_matrix_{t_anchor}.feather`` and serves as
the input ``X`` for all training and evaluation scripts.

Usage::
    python scripts/assemble_features.py --t-anchor YYYY-MM-DD
"""

import argparse
import os
import pandas as pd
import networkx as nx
from core.config import settings
from utils.utils import normalize_date
from utils.profile_helpers import extract_jobs, extract_educations, extract_founded_orgs, extract_company_name
from founder_data import load_founder_profiles

def assemble(t_anchor_str):
    """Assemble the feature matrix for all founders at a given anchor date.

    Reads pre-generated embedding vectors and raw graph edges, computes centrality
    metrics (including Betweenness and Coreness), performs Louvain community
    detection, and assigns founders to 3-year "Mafia" hub buckets. It then
    calculates the **Neighborhood Success Rate** (VC Alpha) by evaluating
    historical outlier success at ``t_anchor``. Finally, it aggregates
    PiT-compliant tabular features like Career Velocity and Serial Founder count.

    Args:
        t_anchor_str (str): Anchor date in ``YYYY-MM-DD`` format. Used to locate
            embeddings (``data/embeddings_{t_anchor_str}.csv``), the weighted graph
            (``data/weighted_graph_{t_anchor_str}.feather``), and to name the output
            (``data/feature_matrix_{t_anchor_str}.feather``).
    """
    t_anchor = pd.to_datetime(t_anchor_str).normalize()
    
    
    # 1. Load Embeddings
    print("Loading Embeddings...")
    emb_path = f"data/embeddings_{t_anchor_str}.csv"
    if not os.path.exists(emb_path):
        print("Embeddings not found! Run train_embeddings.py first.")
        return
    emb_df = pd.read_csv(emb_path)
    emb_df.rename(columns={'founder_id': 'id'}, inplace=True)
    emb_cols = {col: f"emb_{col}" for col in emb_df.columns if col != 'id'}
    emb_df.rename(columns=emb_cols, inplace=True)
    emb_df['id'] = emb_df['id'].astype(str)
    
    # 2. Centrality
    print("Computing Network Centrality...")
    graph_path = f"data/weighted_graph_{t_anchor_str}.feather"
    if not os.path.exists(graph_path):
        print(f"Graph path {graph_path} not found.")
        return
    edges_df = pd.read_feather(graph_path)
    
    # Condense multigraph to simple graph by summing weights
    simple_edges = edges_df.groupby(['u', 'v'])['weight'].sum().reset_index()
    G = nx.Graph()
    for _, row in simple_edges.iterrows():
        G.add_edge(str(row['u']), str(row['v']), weight=row['weight'])
        
    print("Running PageRank...")
    pr = nx.pagerank(G, weight='weight')
    print("Running Degree Centrality...")
    deg = nx.degree_centrality(G)
    
    print("Running Eigenvector Centrality...")
    try:
        eig = nx.eigenvector_centrality(G, max_iter=1000, weight='weight')
    except Exception as e:
        print(f"Eigenvector centrality failed: {e}. Falling back to 0s.")
        eig = {n: 0 for n in G.nodes()}
        
    print("Running Clustering Coefficient...")
    clust = nx.clustering(G, weight='weight')
    
    print("Running Closeness Centrality...")
    close = {}
    if len(G) < 5000:
        for u, v, d in G.edges(data=True):
            if 'weight' in d and d['weight'] > 0:
                d['distance'] = 1.0 / d['weight']
            else:
                d['distance'] = 1.0
        close = nx.closeness_centrality(G, distance='distance')
    else:
        print("Graph too large, bypassing Closeness to save time.")
    
    print("Running Betweenness Centrality...")
    # Betweenness is O(V^3), we use sampled k for large graphs
    k_betweenness = min(50, max(1, len(G))) if len(G) > 5000 else min(1000, max(1, len(G)))
    betw = nx.betweenness_centrality(G, k=k_betweenness, weight='distance', seed=42)
    
    print("Running Coreness...")
    # core_number requires a simple graph without self loops or edge weights breaking its integer assumptions
    G_unweight = nx.Graph(G)
    G_unweight.remove_edges_from(nx.selfloop_edges(G_unweight))
    coreness = nx.core_number(G_unweight)
    
    print("Running Louvain Community Detection...")
    import networkx.algorithms.community as nx_comm
    try:
        communities = nx_comm.louvain_communities(G_unweight, seed=42)
        louvain_map = {}
        for i, comm in enumerate(communities):
            for node in comm:
                louvain_map[node] = i
    except Exception as e:
        print(f"Louvain failed: {e}")
        louvain_map = {n: 0 for n in G.nodes()}
        
    print("Running Degree Assortativity (Average Neighbor Degree)...")
    avg_nd = nx.average_neighbor_degree(G, weight='weight')
    assort_map = {}
    for n in G.nodes():
        node_deg = G.degree(n, weight='weight')
        if avg_nd.get(n, 0) > 0:
            assort_map[n] = float(node_deg) / avg_nd[n]
        else:
            assort_map[n] = 0.0
    
    centrality_df = pd.DataFrame({
        'id': list(pr.keys()),
        'pagerank': list(pr.values()),
        'degree_centrality': [deg[n] for n in pr.keys()],
        'eigenvector_centrality': [eig.get(n, 0) for n in pr.keys()],
        'clustering_coefficient': [clust.get(n, 0) for n in pr.keys()],
        'closeness_centrality': [close.get(n, 0) for n in pr.keys()],
        'betweenness_centrality': [betw.get(n, 0) for n in pr.keys()],
        'coreness': [coreness.get(n, 0) for n in pr.keys()],
        'louvain_community_id': [louvain_map.get(n, 0) for n in pr.keys()],
        'degree_assortativity': [assort_map.get(n, 0) for n in pr.keys()]
    })
    centrality_df['id'] = centrality_df['id'].astype(str)
    # Ensure louvain ID is a categorical string early on
    centrality_df['louvain_community_id'] = "comm_" + centrality_df['louvain_community_id'].astype(str)
    
    # Cache adjacency list before deleting G to massively reduce peak memory
    adj_list = {str(n): [str(x) for x in G.neighbors(n)] for n in G.nodes()}
    
    import gc
    try:
        del G
        del G_unweight
        del pr
        del deg
        del close
        del eig
        del edges_df
    except:
        pass
    gc.collect()
    
    # 3. Tabular Aggregations
    print("Aggregating Point-in-Time Tabular Features...")
    profiles = load_founder_profiles(n=settings.MAX_PROFILES, refresh_cache=False)
    
    # Load Founder IDs mapping from DB to match them
    from utils.utils import get_founder_name_to_id_map  # deferred to avoid circular import
    name_to_id = get_founder_name_to_id_map()
    
    from utils.ml_utils import calculate_founder_success
    from utils.utils import normalize_string
    
    senior_keywords = ['ceo', 'cto', 'founder', 'director', 'vp', 'chief', 'head', 'president']
    tabular_features = []
    
    all_founder_buckets = {}  # f_id -> list of bucket strings
    bucket_counts = {}        # bucket string -> total count globally
    historical_pevs = {}      # f_id -> FSS at t_anchor
    
    for p in profiles:
        f_id = name_to_id.get(p.name)
        if not f_id:
            continue
            
        # Funding
        total_raised = 0.0
        prior_orgs_count = 0
        min_start_date = t_anchor
        
        orgs = extract_founded_orgs(p)
        for org in orgs:
            f_on = normalize_date(getattr(org, "founded_on", None) or getattr(org, "started_on", None))
            if f_on and f_on < t_anchor:
                prior_orgs_count += 1
                if f_on < min_start_date:
                    min_start_date = f_on
                amt = getattr(org, "amount_raised_usd", None) or getattr(org, "funding_total_usd", None) or 0
                try:
                    total_raised += float(amt)
                except Exception:
                    pass
                    
        # Jobs
        senior_roles = 0
        most_recent_role = "None"
        max_job_start = pd.Timestamp.min
        my_buckets = set()
        
        for j in extract_jobs(p):
            j_start = normalize_date(getattr(j, "started_on", None) or getattr(j, "starts_at", None))
            
            if j_start and j_start < t_anchor:
                if j_start < min_start_date:
                    min_start_date = j_start
                    
                title = str(getattr(j, "title", "")).lower()
                if any(kw in title for kw in senior_keywords):
                    senior_roles += 1
                    
                if j_start > max_job_start:
                    max_job_start = j_start
                    most_recent_role = getattr(j, "title", "None") or "None"
                    
                c_name = extract_company_name(j)
                norm_c = normalize_string(c_name) if c_name else None
                if norm_c:
                    bucket_year = j_start.year - (j_start.year % 3)
                    bucket_str = f"{norm_c}_{bucket_year}_{bucket_year+2}"
                    my_buckets.add(bucket_str)
                    
        # Educations
        most_recent_degree = "None"
        max_edu_start = pd.Timestamp.min
        
        for edu in extract_educations(p):
            e_start = normalize_date(getattr(edu, "started_on", None) or getattr(edu, "starts_at", None))
            
            if e_start and e_start < t_anchor:
                if e_start < min_start_date:
                    min_start_date = e_start
                if e_start > max_edu_start:
                    max_edu_start = e_start
                    most_recent_degree = getattr(edu, "degrees", None) or getattr(edu, "degree_name", None) or "None"
                    
        # Profile metrics
        yoe = (t_anchor - min_start_date).days / 365.25 if min_start_date < t_anchor else 0.0
        vel = senior_roles / max(1.0, yoe)
        
        for b in my_buckets:
            bucket_counts[b] = bucket_counts.get(b, 0) + 1
        all_founder_buckets[f_id] = list(my_buckets)
        
        success_info = calculate_founder_success(p, t_anchor)
        historical_pevs[f_id] = success_info['success_score_usd']
        
        tabular_features.append({
            'id': str(f_id),
            'prior_amount_raised_usd': total_raised,
            'prior_senior_roles': senior_roles,
            'most_recent_role': str(most_recent_role),
            'most_recent_degree': str(most_recent_degree),
            'years_of_experience': float(yoe),
            'career_velocity': float(vel),
            'serial_founder_count': int(prior_orgs_count),
        })
        
    tab_df = pd.DataFrame(tabular_features)
    
    # Post-process Mafias
    mafia_col = []
    for tf in tabular_features:
        fid = tf['id']
        buckets = all_founder_buckets.get(fid, [])
        if buckets:
            best_bucket = max(buckets, key=lambda b: bucket_counts[b])
            mafia_col.append(best_bucket)
        else:
            mafia_col.append("none")
    tab_df['primary_mafia_id'] = mafia_col
    
    # Neighborhood Success Rate
    pev_series = pd.Series(historical_pevs)
    if not pev_series.empty:
        thresh = pev_series.quantile(0.85)
        hist_outliers = set(pev_series[(pev_series >= thresh) & (pev_series > 0)].index)
    else:
        hist_outliers = set()
        
    historical_outlier_mapping = {str(k): (1 if k in hist_outliers else 0) for k in historical_pevs.keys()}
    neighborhood_success = {}
    for n, neighbors in adj_list.items():
        if len(neighbors) > 0:
            successes = sum([historical_outlier_mapping.get(str(nb), 0) for nb in neighbors])
            neighborhood_success[str(n)] = float(successes) / len(neighbors)
        else:
            neighborhood_success[str(n)] = 0.0
            
    centrality_df['neighborhood_success_rate'] = centrality_df['id'].map(neighborhood_success).fillna(0.0)
    
    # 4. Merge All
    print("Merging features...")
    final_df = tab_df.merge(emb_df, on='id', how='left')
    final_df = final_df.merge(centrality_df, on='id', how='left')
    
    final_df['pagerank'] = final_df['pagerank'].fillna(0)
    final_df['degree_centrality'] = final_df['degree_centrality'].fillna(0)
    final_df['eigenvector_centrality'] = final_df['eigenvector_centrality'].fillna(0)
    final_df['clustering_coefficient'] = final_df['clustering_coefficient'].fillna(0)
    final_df['closeness_centrality'] = final_df['closeness_centrality'].fillna(0)
    
    for col in emb_df.columns:
        if col != 'id':
            final_df[col] = final_df[col].fillna(0)
            
    out_path = f"data/feature_matrix_{t_anchor_str}.feather"
    final_df['most_recent_role'] = final_df['most_recent_role'].astype(str)
    final_df['most_recent_degree'] = final_df['most_recent_degree'].astype(str)
    
    final_df.to_feather(out_path)
    print(f"Feature matrix saved to {out_path} with shape {final_df.shape}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--t-anchor", type=str, required=True, help="Anchor date YYYY-MM-DD")
    args = parser.parse_args()
    assemble(args.t_anchor)
